easy_admin:
    site_name: 'Pokeshine'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - name
                    - lastname
                    - username
                    - email
                    - { property: 'superAdmin', type: 'toggle' }
                actions: ['-delete']
            form:
                form_options: { csrf_protection: false }
                fields:
                    - name
                    - lastname
                    - username
                    - { property: 'email', type: 'email' }
                actions: ['-delete']
        Pokemon:
            class: App\Entity\Pokemon
            list:
                fields:
                    - number
                    - name
                    - generation
                    - { property: 'pokemonTypes' }
            form:
                form_options: { csrf_protection: false }
                fields:
                    - number
                    - name
                    - description
                    - generation
                    - { property: 'pokemonTypes', label: 'Types', type_options: { 'by_reference': false } }
                actions: ['-delete']