<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{
    /**
     * @param int $offset
     * @param int $limit
     *
     * @return array
     */
    public function getPokemons(int $offset = 0, int $limit = 50): array
    {
        return $this->createQueryBuilder('p')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
