#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

user:
    type: rest
    prefix: /api/v1
    resource: App\Controller\UserController

default:
    type: rest
    prefix: /api/v1
    resource: App\Controller\DefaultController

login:
    type: rest
    prefix: /api/v1
    resource: App\Controller\LoginController

pokemon:
    type: rest
    prefix: /api/v1
    resource: App\Controller\PokemonController

Shiny:
    type: rest
    prefix: /api/v1
    resource: App\Controller\ShinyController

# EasyAdminBundle Routing
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin