# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true    # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.user.user_handler:
        class: App\Services\User\UserHandler
        arguments:
            - '@security.token_storage'
            - '@form.factory'
            - '@fos_user.user_manager'
        public: true

    app.shiny.shiny_handler:
        class: App\Services\Shiny\ShinyHandler
        arguments:
            - '@security.token_storage'
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@app.file_uploader.shiny'
        public: true

    app.repository.user_repository:
        class: App\Repository\UserRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['App\Entity\User']
        public: true

    app.repository.pokemon_repository:
        class: App\Repository\PokemonRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['App\Entity\Pokemon']
        public: true

    app.user.password_handler:
        class: App\Services\User\PasswordHandler
        arguments:
            - '@fos_user.util.token_generator'
            - '%fos_user.resetting.token_ttl%'
            - '@fos_user.user_manager'
            - '@form.factory'
        public: true

    app.user.avatar_handler:
        class: App\Services\User\AvatarHandler
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@app.file_uploader.avatar'
        public: true

    app.user.current_hunt_handler:
        class: App\Services\User\CurrentHuntHandler
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
        public: true

    app.file_uploader.avatar:
        class: App\Services\FileUploader
        arguments:
            $targetDir: '%kernel.project_dir%/public/uploads/avatars'
        public: true

    app.file_uploader.shiny:
        class: App\Services\FileUploader
        arguments:
            $targetDir: '%kernel.project_dir%/public/uploads/shinies'
        public: true